### ISSUE TITLE
Socket.IO

### ISSUE THREAD

**Issue by MarioHofer** [HelixOne/letojs#1]
Hej there.

Did you get Socket.IO running inside your Angular2 app?

I tried for a long time but didn't get it running. It would be fab, if you can write me a quick line back. 

Thanks!

- Mario

**Comment by helixten** [comment]
Yes take a look at the "task" on the dev branch. It uses the Observable.fromEvent

**Comment by MarioHofer** [comment]
Thanks for the reply! Yes, I've seen that. But inside you index html the Socket.IO JavaScript file is commented out. Do you make this file accessible anywhere else?

**Comment by helixten** [comment]
The import statement at the top of the task loads the socketio.js file
